version: "3.8"

services:
  database:
    container_name: database
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tournament_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tournament_db"]
      interval: 5s
      retries: 5

  backend:
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://user:password@database:5432/tournament_db"
    entrypoint: ["/bin/sh", "-c", "npx prisma migrate deploy && npm start"]

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
