version: "3.8"

services:
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tournament_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tournament_db"]
      interval: 5s
      retries: 5
      timeout: 5s

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile

    depends_on:
      database:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://user:password@database:5432/tournament_db"
    command: ["sh", "-c", "npx prisma db push && node index.js"]

  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local
